## Numpy Arrays


Numpy is used for mathematical calculations of large amont of data


In [1]:
import numpy as np

In [4]:
a1 = np.array([2,4,6,8])
a1

array([2, 4, 6, 8])

In [6]:
a1.ndim

1

In [7]:
a1.shape

(4,)

In [8]:
b = [4.5, 5.1, 7.2]

In [9]:
type(b)

list

In [10]:
b1 = np.array(b)

In [11]:
b1

array([4.5, 5.1, 7.2])

In [12]:
b1.ndim

1

In [13]:
b1.shape

(3,)

In [14]:
c = [[1,2,3,4],
     [5,6,7,8]]

In [15]:
type(c)

list

In [16]:
c1 = np.array(c)

In [17]:
c1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
c1.ndim

2

In [19]:
c1.shape

(2, 4)

In [20]:
d = [[[1,2,3,4],
     [5,6,7,8]],
     
     [[11,12,13,14],
     [15,16,17,18]],

     [[21,22,23,24],
      [25,26,27,28]]]

In [21]:
d1 = np.array(d)

In [22]:
d1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28]]])

In [23]:
d1.ndim

3

In [24]:
d1.shape

(3, 2, 4)

# List Vs Array Mathematical Operations on single element

In [25]:
g = [1,2,3,4]

In [26]:
g*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [27]:
g*1.5

TypeError: can't multiply sequence by non-int of type 'float'

In [28]:
g1 = []
for i in g:
    g1.append(i*3)

In [29]:
g1

[3, 6, 9, 12]

###using numpy

In [30]:
h = np.array(g)

In [31]:
h

array([1, 2, 3, 4])

In [32]:
j = 3*h

In [33]:
j

array([ 3,  6,  9, 12])

In [34]:
k = 5.6*h

In [35]:
k

array([ 5.6, 11.2, 16.8, 22.4])

In [36]:
m = 1.2*h + 2.3

In [37]:
m

array([3.5, 4.7, 5.9, 7.1])

## Aggregation operations sum, mean, median, max, min

In [38]:
a = [1,2,3,4]

In [39]:
np.prod(a)

np.int64(24)

In [40]:
np.mean(a)

np.float64(2.5)

In [41]:
np.sum(a)

np.int64(10)

In [42]:
np.mean(a)

np.float64(2.5)

In [43]:
np.median(a)

np.float64(2.5)

In [44]:
b = [[3,2,4,5],
     [7,8,9,10],
     [11,12,13,14]]

In [45]:
np.sum(b)

np.int64(98)

In [46]:
np.sum(b, axis=0)

array([21, 22, 26, 29])

In [47]:
np.sum(b, axis=1)

array([14, 34, 50])

In [48]:
np.mean(b)

np.float64(8.166666666666666)

In [49]:
np.mean(b, axis=0)

array([7.        , 7.33333333, 8.66666667, 9.66666667])

In [53]:
np.max(b, axis=1)

array([ 5, 10, 14])

In [54]:
np.max(b, axis=0)

array([11, 12, 13, 14])

In [52]:
b

[[3, 2, 4, 5], [7, 8, 9, 10], [11, 12, 13, 14]]

# Range Function

In [56]:
b = np.arange(start=2, stop=10, step=2)

In [57]:
b

array([2, 4, 6, 8])